name: Pylint

on: [push]
permissions:
  contents: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          echo "My Test.Key is ${{secrets.TEST}}"
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git add report.txt
          git commit -am "Automated report"
          git push

