name: LLM_Documenter

on: [push]
permissions:
  contents: write

jobs:
  document_changed_python_files:
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.python_script.outputs.changed_files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Read changed .py in commit
        id: python_script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          python3.10 src/read_changed_files.py

      - name: Commit files with added dummyDS
        if: steps.python_script.outputs.changed_files != ''
        run: |
          echo "Generating list of outputs...!"
          for OUTPUT in "${{ steps.python_script.outputs.changed_files }}"; do
            python3.10 src/abstract_tree.py ${{ secrets.GROQ_API_KEY }} $OUTPUT
            autopep8 --in-place --aggressive $OUTPUT
            black $OUTPUT
            git add $OUTPUT
          done
      - name: Init Sphinx documentation
        run: |
          if ! test -f "docs/index.rst"; then
            mkdir -p docs
            sphinx-quickstart --sep --makefile --ext-autodoc --project="${{ github.repository }}" --author="LLM-Bot" --release="0.0.1" --language="en" docs
          fi
      - name: Render sphinx
        run: |
          sphinx-build -M html ./docs/source ./docs
          git add -f ./docs/*
      - name: Commit files
        run: | 
          echo "Committing updated .py files...!"
          git config --global user.email "you@example.com"
          git config --global user.name "LLM-Docstring-Agent"
          git commit -am "LLM-documented files pushed"
          git push
