name: LLM_Documenter

on: [push]
permissions:
  contents: write

jobs:
  document_changed_python_files:
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.python_script.outputs.changed_files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install python dependencies
        run: pip install -r .github/workflows/requirements.txt

      - name: Read changed .py in commit
        id: python_script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          python3.10 .github/workflows/read_changed_files.py

      - name: Commit files with added dummyDS
        if: steps.python_script.outputs.changed_files != ''
        run: |
          echo "Generating list of outputs...!"
          for OUTPUT in "${{ steps.python_script.outputs.changed_files }}"; do
<<<<<<< HEAD
            python3.10 .github/workflows/abstract_tree.py ${{ secrets.CROQUE_TOKEN }} $OUTPUT
            autopep8 --in-place --aggressive $OUTPUT
            git add $OUTPUT
=======
            python3.10 src/abstract_tree.py $OUTPUT
	    git add $OUTPUT
>>>>>>> b1ab4ac511619953a3ea1639c112eb7217ac6043
          done
          echo "Committing updated .py files...!"
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git commit -am "LLM-documented files pushed"
          git push
