name: LLM_Documenter

on: [workflow_dispatch]
permissions:
  contents: write

env:
  SOURCE_PATH: 'src'

jobs:
  document_changed_python_files:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.python_script.outputs.changed_files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: New Branch creation
        run: |
          git checkout -b commented_branch

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install python dependencies
        run: pip install -r .github/workflows/requirements.txt

      - name: Read changed .py in commit
        id: python_script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          python3.10 .github/workflows/read_changed_files.py $SOURCE_PATH

      - name: Commit files with added dummyDS
        if: steps.python_script.outputs.changed_files != ''
        run: |
          echo "Generating list of outputs...!"
          for OUTPUT in "${{ steps.python_script.outputs.changed_files }}"; do
            python3.10 .github/workflows/abstract_tree.py ${{ secrets.GROQ_API_KEY }} $OUTPUT
            autopep8 --in-place --aggressive $OUTPUT
            black $OUTPUT
            git add $OUTPUT
          done
      - name: Init Sphinx documentation
        run: |
          rm -R docs
          if ! test -f "docs/Makefile"; then
            mkdir -p docs
            sphinx-quickstart --sep --makefile --ext-autodoc --project="${{ github.event.repository.name }}" --author="LLM-Bot" --release="0.0.1" --language="en" docs
            echo "import sys, os" >> ./docs/source/conf.py
            echo "sys.path.insert(0, os.path.abspath('../..'))" >> ./docs/source/conf.py
            echo "extensions += ['sphinx.ext.napoleon', 'sphinx_rtd_theme', 'sphinx.ext.githubpages']" >> ./docs/source/conf.py
            echo "html_theme = 'sphinx_rtd_theme'" >> ./docs/source/conf.py
          fi
      - name: Render sphinx
        run: |
          sphinx-apidoc -f -o docs/source ./
          python3.10 .github/workflows/readme.py ${{ secrets.GROQ_API_KEY }} $SOURCE_PATH
          sphinx-build -M html ./docs/source ./docs
          cp -r ./docs/html/* ./docs/
          rm -r ./docs/html
          git add -f ./docs/*
      - name: Commit files
        run: | 
          echo "Committing updated .py files...!"
          git config --global user.email "you@example.com"
          git config --global user.name "LLM-Docstring-Agent"
          git status --short
          git commit -m "LLM-documented files pushed"
          rm -f docs/.nojekyll
          git add ./docs/.nojekyll
          git push origin commented_branch
          touch ./docs/.nojekyll
          git add -f ./docs/.nojekyll
          git commit -m "Add .nojekyll"
          git push origin commented_branch
